// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW54ldfVMyjmMOdEn0XETGfqAHOas9tvc',
    appId: '1:192243418994:web:b596d60a89452ea36ebfeb',
    messagingSenderId: '192243418994',
    projectId: 'todolist-a9e59',
    authDomain: 'todolist-a9e59.firebaseapp.com',
    storageBucket: 'todolist-a9e59.appspot.com',
    measurementId: 'G-4H0J5EHG3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSZRMk3HHd3axM_TWOYvr4sLtKMVnSgMQ',
    appId: '1:192243418994:android:07a0e4091c2b683d6ebfeb',
    messagingSenderId: '192243418994',
    projectId: 'todolist-a9e59',
    storageBucket: 'todolist-a9e59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-zSCELILaQLE9ru6KRfWVu5D6D8b8z1g',
    appId: '1:192243418994:ios:14da0b9868b81f5e6ebfeb',
    messagingSenderId: '192243418994',
    projectId: 'todolist-a9e59',
    storageBucket: 'todolist-a9e59.appspot.com',
    iosClientId: '192243418994-jam7bn6f6jokt8s407pth4iqjn1b2liv.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-zSCELILaQLE9ru6KRfWVu5D6D8b8z1g',
    appId: '1:192243418994:ios:6bf4d7426c08f0b16ebfeb',
    messagingSenderId: '192243418994',
    projectId: 'todolist-a9e59',
    storageBucket: 'todolist-a9e59.appspot.com',
    iosClientId: '192243418994-jju4qvtpsnbir7o2vdeq9263btmetn3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist.RunnerTests',
  );
}
